import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.TelegramBotsApi;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        Logger log = LoggerFactory.getLogger(App.class);
        log.info("main started");
        ApiContextInitializer.init();
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi();

        try {
            telegramBotsApi.registerBot(new BotService());
            log.info("bot registered");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
