import connector.Connector;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.TelegramBotsApi;
import org.telegram.telegrambots.api.objects.Chat;

import java.sql.Connection;
import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

//        BasicCommand basicCommand = new BasicCommand();
//        Conversation conversation = new Conversation();
//
//        long chatId = -1001123471924l;
//
//        Connection connection = null;
//        try {
//            connection = Connector.getConnection();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//
//
//        basicCommand.table(connection, chatId, "", null);

        Logger log = LoggerFactory.getLogger(App.class);
        log.info("main started");
        ApiContextInitializer.init();
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi();

        try {
            telegramBotsApi.registerBot(new BotService());
            log.info("bot registered");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
