import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.TelegramBotsApi;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Logger log = LoggerFactory.getLogger(App.class);
        System.out.println("hello bot");
        log.info("main started");
        ApiContextInitializer.init();
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi();

        try {
            telegramBotsApi.registerBot(new Expert());
            System.out.println("registered bot");
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("after");
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
